
import React from 'react';
import { 
  Truck, 
  Construction, 
  Trash2, 
  HardHat, 
  Ambulance, 
  Car, 
  ClipboardCheck,
  User,
  Shield,
  MapPin,
  Clock,
  ChevronRight,
  Save,
  Download,
  ArrowLeft,
  LayoutDashboard,
  FileText,
  Briefcase,
  UserCheck,
  UserX,
  Tractor
} from 'lucide-react';

export const ACCESS_POINTS = ['ACP1', 'ACP2', 'ACP3', 'ACP4', 'ACP5', 'ACP6'];

export const VEHICLE_TYPES = [
  { id: 'Tug', label: 'Remorqueur', labelAr: 'قاطرة', icon: <Tractor className="w-6 h-6" /> },
  { id: 'Truck', label: 'Camion', labelAr: 'شاحنة', icon: <Truck className="w-6 h-6" /> },
  { id: 'Crane', label: 'Grue mobile', labelAr: 'رافعة متنقلة', icon: <Construction className="w-6 h-6" /> },
  { id: 'Forklift', label: 'Chariot élévateur', labelAr: 'رافعة شوكية', icon: <HardHat className="w-6 h-6" /> },
  { id: 'Grader', label: 'Niveleuse', labelAr: 'مهدِّدة', icon: <Construction className="w-6 h-6" /> },
  { id: 'Ambulance', label: 'Ambulance', labelAr: 'إسعاف', icon: <Ambulance className="w-6 h-6" /> },
  { id: 'Other', label: 'Autre', labelAr: 'آخر', icon: <Car className="w-6 h-6" /> },
];

export const ICONS = {
  User: <User className="w-5 h-5" />,
  Shield: <Shield className="w-5 h-5" />,
  MapPin: <MapPin className="w-5 h-5" />,
  Clock: <Clock className="w-5 h-5" />,
  Next: <ChevronRight className="w-5 h-5" />,
  Save: <Save className="w-5 h-5" />,
  Download: <Download className="w-5 h-5" />,
  Back: <ArrowLeft className="w-5 h-5" />,
  Delete: <Trash2 className="w-5 h-5" />,
  Dashboard: <LayoutDashboard className="w-5 h-5" />,
  History: <FileText className="w-5 h-5" />,
  Company: <Briefcase className="w-5 h-5" />,
  Announced: <UserCheck className="w-5 h-5" />,
  NotAnnounced: <UserX className="w-5 h-5" />
};

export const TRANSLATIONS = {
  FR: {
    title: 'ATHENA SURVEILLANCE',
    subtitle: 'Contrôle d\'Accès Sécurisé',
    chefPoste: 'Nom du chef de poste',
    accessPoint: 'Point d\'accès',
    next: 'Suivant',
    back: 'Retour',
    save: 'Enregistrer',
    typeSelection: 'Type d\'entrée',
    visitor: 'Visiteur',
    vehicle: 'Véhicule',
    history: 'Historique',
    export: 'Exporter',
    visitorForm: 'Informations Visiteur',
    vehicleForm: 'Informations Véhicule',
    name: 'Nom du visiteur',
    personVisited: 'Personne visitée',
    cin: 'N° CIN',
    registration: 'Immatriculation',
    societe: 'Société',
    entryTime: 'Heure d\'entrée (HE)',
    exitTime: 'Heure de sortie (HS)',
    destination: 'Destination',
    observation: 'Observations',
    announced: 'Visiteur annoncé',
    notAnnounced: 'Non annoncé',
    vehicleType: 'Type de véhicule',
    driverName: 'Nom du chauffeur',
    bonNumber: 'N° de bon',
    success: 'Enregistré avec succès',
    noData: 'Aucune donnée',
    date: 'Date du jour',
    announcedStatus: 'Statut du visiteur'
  },
  AR: {
    title: 'أثينا للمراقبة',
    subtitle: 'مراقبة الدخول الآمن',
    chefPoste: 'اسم رئيس المركز',
    accessPoint: 'نقطة الوصول',
    next: 'التالي',
    back: 'رجوع',
    save: 'حفظ',
    typeSelection: 'نوع الدخول',
    visitor: 'زائر',
    vehicle: 'مركبة',
    history: 'السجل',
    export: 'تصدير',
    visitorForm: 'معلومات الزائر',
    vehicleForm: 'معلومات المركبة',
    name: 'اسم الزائر',
    personVisited: 'الشخص المزار',
    cin: 'رقم بطاقة التعريف',
    registration: 'رقم التسجيل',
    societe: 'الشركة',
    entryTime: 'وقت الدخول',
    exitTime: 'وقت الخروج',
    destination: 'الوجهة',
    observation: 'ملاحظات',
    announced: 'زائر معلن',
    notAnnounced: 'غير معلن',
    vehicleType: 'نوع المركبة',
    driverName: 'اسم السائق',
    bonNumber: 'رقم الوصل',
    success: 'تم الحفظ بنجاح',
    noData: 'لا توجد بيانات',
    date: 'تاريخ اليوم',
    announcedStatus: 'حالة الزائر'
  }
};
